# Generated by Django 4.2.7 on 2024-09-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_otp',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
